[package]
name = "discord_bot"
version = "0.1.0"
authors = ["pise"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.9.0-rc.0"
tokio = "0.2"
